# Generated by Django 6.0.1 on 2026-01-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('products_consumeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('hogar', 'Hogar'), ('salud', 'Salud'), ('educacion', 'Educación')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_products', to='expenses.expense')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_products', to='products_consumeds.productconsumed')),
            ],
        ),
    ]
