# Generated by Django 5.2.2 on 2025-08-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
