# Generated by Django 5.1 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_networks', '0002_alter_socialnetwork_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
