import {
  DashboardIcon,
  PersonIcon,
  GearIcon,
  BarChartIcon,
  FileTextIcon,
  EnvelopeClosedIcon,
  ChatBubbleIcon,
  CalendarIcon,
  LockClosedIcon,
  CardStackIcon,
  ReaderIcon,
  ArchiveIcon,
  BellIcon,
  BookmarkIcon,
  Share2Icon,
  CheckboxIcon,
  MixerHorizontalIcon,
  GitHubLogoIcon,
  LinkedInLogoIcon,
  TwitterLogoIcon,
  InstagramLogoIcon,
  MagicWandIcon,
  VideoIcon,
  MinusIcon,
  GlobeIcon,
  IdCardIcon,
  PlusIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  Pencil1Icon,
  TrashIcon,
  Cross2Icon,
  CheckCircledIcon,
  ExclamationTriangleIcon,
  Link2Icon,
  ArrowUpIcon, 
  ArrowDownIcon,
  Cross1Icon, 
  SunIcon,
  MoonIcon,
  ExitIcon,
  RocketIcon,
  EyeOpenIcon,
  EyeClosedIcon,
  MobileIcon,
  HomeIcon,
  MagnifyingGlassIcon,
  CrossCircledIcon,
  ImageIcon,
  PaperPlaneIcon
} from '@radix-ui/react-icons'

export const Icons = {
  dashboard: DashboardIcon,
  user: PersonIcon,
  settings: GearIcon,
  analytics: BarChartIcon,
  file: FileTextIcon,
  mail: EnvelopeClosedIcon,
  chat: ChatBubbleIcon,
  calendar: CalendarIcon,
  security: LockClosedIcon,
  finance: CardStackIcon,
  content: ReaderIcon,
  archive: ArchiveIcon,
  notification: BellIcon,
  bookmark: BookmarkIcon,
  share: Share2Icon,
  task: CheckboxIcon,
  menu: MagicWandIcon,
  filter: MixerHorizontalIcon,
  plusIcon: PlusIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  edit: Pencil1Icon,
  delete: TrashIcon,
  close: Cross2Icon,
  check: CheckCircledIcon,
  error: ExclamationTriangleIcon,
  arrowUp: ArrowUpIcon,
  arrowDown: ArrowDownIcon,
  crossIcon: Cross1Icon,
  sunIcon: SunIcon,
  moonIcon: MoonIcon,
  exitIcon: ExitIcon,
  rocketIcon: RocketIcon,
  eyeOpenIcon: EyeOpenIcon,
  eyeClosedIcon: EyeClosedIcon,
  mobileIcon: MobileIcon,
  homeIcon: HomeIcon,
  magnifyingGlassIcon: MagnifyingGlassIcon,
  crossCircledIcon: CrossCircledIcon,
  imageIcon: ImageIcon,
  paperPlaneIcon: PaperPlaneIcon,

  // Redes sociales
  github: GitHubLogoIcon,
  linkedin: LinkedInLogoIcon,
  twitter: TwitterLogoIcon,
  instagram: InstagramLogoIcon,
  youtube: VideoIcon,
  tiktok: MinusIcon,
  facebook: GlobeIcon,
  link: Link2Icon,
  otro: GlobeIcon,

  // Finance
  creditCard: CardStackIcon,
  money: IdCardIcon,
}