import {
  DashboardIcon,
  PersonIcon,
  GearIcon,
  BarChartIcon,
  FileTextIcon,
  EnvelopeClosedIcon,
  ChatBubbleIcon,
  CalendarIcon,
  LockClosedIcon,
  CardStackIcon,
  ReaderIcon,
  ArchiveIcon,
  BellIcon,
  BookmarkIcon,
  Share2Icon,
  CheckboxIcon,
  MixerHorizontalIcon,
} from '@radix-ui/react-icons'

export const Icons = {
  dashboard: DashboardIcon,
  user: PersonIcon,
  settings: GearIcon,
  analytics: BarChartIcon,
  file: FileTextIcon,
  mail: EnvelopeClosedIcon,
  chat: ChatBubbleIcon,
  calendar: CalendarIcon,
  security: LockClosedIcon,
  finance: CardStackIcon,
  content: ReaderIcon,
  archive: ArchiveIcon,
  notification: BellIcon,
  bookmark: BookmarkIcon,
  share: Share2Icon,
  task: CheckboxIcon,
  filter: MixerHorizontalIcon,
}