# Generated by Django 5.1 on 2026-04-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('hogar', 'Hogar'), ('salud', 'Salud'), ('educacion', 'Educación')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
