# Generated by Django 5.1 on 2026-05-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_category_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_real',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('hogar', 'Hogar'), ('salud', 'Salud'), ('educacion', 'Educación'), ('alimentacion', 'Alimentación')], db_index=True, max_length=20),
        ),
    ]
