# Generated by Django 5.1 on 2026-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_is_real_expense_is_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('hogar', 'Hogar'), ('servicios', 'Servicios públicos'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('compras', 'Compras'), ('deudas', 'Pago de deudas'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión'), ('mascotas', 'Mascotas'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('viajes', 'Viajes'), ('impuestos', 'Impuestos'), ('seguros', 'Seguros'), ('regalos', 'Regalos'), ('suscripciones', 'Suscripciones'), ('otros', 'Otros')], db_index=True, max_length=20),
        ),
    ]
