# Generated by Django 5.1 on 2026-05-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_title_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_real',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='is_test',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('test', 'Test'), ('production', 'Producción')], db_index=True, default='production', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('alimentacion', 'Alimentación'), ('transporte', 'Transporte'), ('vivienda', 'Vivienda'), ('servicios', 'Servicios públicos'), ('salud', 'Salud'), ('educacion', 'Educación'), ('entretenimiento', 'Entretenimiento'), ('compras', 'Compras'), ('ropa', 'Ropa'), ('tecnologia', 'Tecnología'), ('viajes', 'Viajes'), ('mascotas', 'Mascotas'), ('suscripciones', 'Suscripciones'), ('deudas', 'Pago de deudas'), ('ahorro', 'Ahorro'), ('inversion', 'Inversión'), ('impuestos', 'Impuestos'), ('seguros', 'Seguros'), ('regalos', 'Regalos'), ('otros', 'Otros')], db_index=True, max_length=20),
        ),
    ]
