# Generated by Django 5.1 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expense_is_real_remove_expense_is_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
