# Generated by Django 5.1 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_saving_end_date_alter_saving_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
