# Generated by Django 5.1 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_alter_income_category_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
