# Generated by Django 5.2.2 on 2025-08-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_email_user_correo_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ciudad',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='empresa',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='creado_en',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cedula',
            new_name='national_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telefono',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='prefijo',
            new_name='phone_prefix',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='foto',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='rol',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verificado',
            new_name='verified',
        ),
    ]
