# Generated by Django 5.1 on 2026-04-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_date_joined_user_created_at_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='descripction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
