# Generated by Django 5.2.2 on 2025-08-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_direccion_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='national_id',
            new_name='cedula',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_at',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='pais',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_prefix',
            new_name='prefijo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='verificado',
        ),
    ]
