# Generated by Django 5.1 on 2026-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_descripction_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='descripction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
