# Generated by Django 5.1 on 2026-04-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_descripction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='descripction',
            new_name='description',
        ),
    ]
