# Generated by Django 5.1 on 2026-05-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_descripction_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('free', 'Free'), ('premium', 'Premium')], max_length=10),
        ),
    ]
